INSERT INTO EMPLOYEE (id, FIRST_NAME,LAST_NAME,ADDRESS,SALARY,MANAGER_ID) VALUES (1, 'JAY','CHAND','BIHAR',70,null);
INSERT INTO EMPLOYEE (id, FIRST_NAME,LAST_NAME,ADDRESS,SALARY,MANAGER_ID) VALUES (2, 'RAM','SINGH','DELHI',50,1);
INSERT INTO EMPLOYEE (id, FIRST_NAME,LAST_NAME,ADDRESS,SALARY,MANAGER_ID) VALUES (3, 'DEV','GUPTA','NOIDA',55,1);